"""Three output backends: terminal scaffold, Claude Code subagents, dashboard PendingAction.

All three accept the same `SwarmDesign` and emit artifacts where the user
expects them. Idempotent — running twice with the same design overwrites
files (except project root, which is preserved).
"""
from __future__ import annotations

import json
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

from .design import SwarmDesign


# ---------------------------------------------------------------------------
# 1. Terminal scaffold — examples/<name>/run.py + heartbeat
# ---------------------------------------------------------------------------

_TERMINAL_RUN_PY = '''"""{description}

Run with:  python examples/{name}/run.py
Or, with the CLI: forge run {name}
"""
from __future__ import annotations
import asyncio

from forge import (
    AgentDef, AgentLoop, HookBus, Telemetry, ToolRegistry, attach_healing,
    make_provider,
)


AGENTS = {agents_repr}


async def main() -> None:
    hooks = HookBus()
    Telemetry(path=".forge/{name}/telemetry.jsonl").attach(hooks)
    attach_healing(hooks)
    tools = ToolRegistry()
    # TODO: register the tools each agent needs in `tools` —
    # forge ships builtins (fs_read, fs_write, web_search, web_fetch).
    # For MCP/Composio tools, see forge/tools/mcp_client.py.

    for spec in AGENTS:
        provider = make_provider(spec["profile"])
        agent = AgentDef(name=spec["name"], instructions=spec["instructions"],
                         profile=spec["profile"])
        loop = AgentLoop(agent=agent, provider=provider, tools=tools, hooks=hooks)
        result = await loop.run(input_text="Begin.")
        print(f"[{{spec['name']}}] {{result.text[:200]}}")


if __name__ == "__main__":
    asyncio.run(main())
'''

_TERMINAL_README = '''# {name}

{description}

## Agents
{agents_md}

## Run
```bash
python examples/{name}/run.py
```

{schedule_md}
'''


def write_terminal_project(design: SwarmDesign, root: Path) -> list[Path]:
    """Write `examples/<name>/{run.py, README.md}` and an optional heartbeat."""
    root = Path(root)
    target = root / "examples" / design.name
    target.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    agents_repr = json.dumps(
        [{"name": a.name, "role": a.role, "instructions": a.instructions,
          "profile": a.profile, "tools": a.tools} for a in design.agents],
        indent=4,
    )
    (target / "run.py").write_text(_TERMINAL_RUN_PY.format(
        description=design.description.replace('"""', '\\"\\"\\"'),
        name=design.name,
        agents_repr=agents_repr,
    ))
    written.append(target / "run.py")

    agents_md = "\n".join(
        f"- **{a.name}** ({a.role}, `{a.profile}`)" for a in design.agents
    )
    schedule_md = (
        f"## Schedule\n\nThis swarm runs on cron `{design.schedule}` via the heartbeat "
        f"at `examples/{design.name}/heartbeats/run.md`."
        if design.schedule else
        "## Schedule\n\nOn-demand only. Add a heartbeat under `heartbeats/` to schedule."
    )
    (target / "README.md").write_text(_TERMINAL_README.format(
        name=design.name, description=design.description,
        agents_md=agents_md, schedule_md=schedule_md,
    ))
    written.append(target / "README.md")

    if design.schedule:
        hb_dir = target / "heartbeats"
        hb_dir.mkdir(exist_ok=True)
        hb_path = hb_dir / "run.md"
        hb_path.write_text(
            f"---\nschedule: \"{design.schedule}\"\nagent: {design.name}\n---\n\n"
            f"# {design.name} heartbeat\n\n"
            f"Runs the swarm on cron `{design.schedule}`.\n\n"
            f"```bash\npython examples/{design.name}/run.py\n```\n"
        )
        written.append(hb_path)

    (target / "design.json").write_text(design.to_json())
    written.append(target / "design.json")

    return written


# ---------------------------------------------------------------------------
# 2. Claude Code subagents — .claude/agents/<name>.md per agent
# ---------------------------------------------------------------------------

_CLAUDE_SUBAGENT = """---
name: {name}
description: {role} — {description_short}
tools: {tools_list}
---

{instructions}

## Provider hint
This agent was designed for the `{profile}` profile in forge. When running
inside Claude Code (Anthropic), you can ignore the profile field — the host
session's model is used. The name + role + instructions above are what
matter.

## Source
Generated by `forge new` from this description:

> {description}
"""


def write_claude_subagents(design: SwarmDesign, repo_root: Path) -> list[Path]:
    """Write `<repo>/.claude/agents/<name>.md` per agent. Drop-in for any
    Claude Code session."""
    repo_root = Path(repo_root)
    agents_dir = repo_root / ".claude" / "agents"
    agents_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    short_desc = (design.description[:80] + "…") if len(design.description) > 80 else design.description
    for spec in design.agents:
        path = agents_dir / f"{design.name}_{spec.name}.md"
        path.write_text(_CLAUDE_SUBAGENT.format(
            name=f"{design.name}_{spec.name}",
            role=spec.role,
            description_short=short_desc,
            description=design.description,
            tools_list=", ".join(spec.tools) if spec.tools else "(inherits parent)",
            instructions=spec.instructions,
            profile=spec.profile,
        ))
        written.append(path)
    # README so the user knows where these came from
    readme = agents_dir / f"{design.name}.README.md"
    readme.write_text(
        f"# {design.name} (Claude Code subagent bundle)\n\n"
        f"{design.description}\n\n"
        "These markdown files are Claude Code agent definitions. "
        "Invoke them in Claude Code via `/agents` or by mentioning the agent "
        "name. They were generated by `forge new` — re-run that to refresh.\n"
    )
    written.append(readme)
    return written


# ---------------------------------------------------------------------------
# 3. Dashboard — POST a propose_start_project PendingAction
# ---------------------------------------------------------------------------

def propose_dashboard_action(
    design: SwarmDesign, dashboard_url: str, sync_token: str,
    *, transport=None,
) -> str:
    """POST /sync/propose-design with a custom-template payload. Returns the
    PendingAction id for the user to Approve in the workspace.

    Requires the dashboard server to support `POST /sync/propose-design`
    (added alongside this scaffolder).
    """
    body = json.dumps({
        "kind": "start_project",
        "payload": {
            "name": design.name,
            "template": "custom",
            "description": design.description,
            "design_json": design.to_json(),
        },
    }).encode("utf-8")
    headers = {
        "Content-Type": "application/json",
        "X-Forge-Sync-Token": sync_token,
    }
    target = dashboard_url.rstrip("/") + "/sync/propose-design"
    if transport is not None:
        return transport(target, body, headers).get("id", "")
    req = urllib.request.Request(target, data=body, headers=headers, method="POST")
    with urllib.request.urlopen(req, timeout=30) as resp:  # nosec — own server
        data = json.loads(resp.read().decode("utf-8"))
    return data.get("id", "")
